---
name: run ibm.power_aix collection sanity tests

# run sanity test during pull request to dev-collection
on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ########################################################################
  # sanity test
  # - makes sure that the collection passes the ansible sanity tests
  ########################################################################
  sanity-test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ansible-version: ['4', '5']
        python-version: ['3.8', '3,9', '3.10', '3.11', '3.12']
        include:
          # - ansible-version: 'devel'
          #   python-version: '3.11'
          # - ansible-version: 'devel'
          #   python-version: '3.12'
          - ansible-version: '2.9'
            python-version: '3.8'
          - ansible-version: '3'
            python-version: '3.9'

    name: running sanity tests with ansible ${{ matrix.ansible-version }} and python ${{ matrix.python-version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          path: schamola/test-github-actions

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Create a venv
      #   run: |
      #     python3 -m venv sanity-test &&
      #     source sanity-test/bin/activate

      - name: install ansible ${{ matrix.ansible-version }}
        if: ${{ matrix.ansible-version != 'devel' }}
        run: |
          pip install ansible==${{ matrix.ansible-version }}.* --user

      - name: install ansible ${{ matrix.ansible-version }}
        if: ${{ matrix.ansible-version == 'devel' }}
        run: |
          python -m pip install ansible==${{ matrix.ansible-version }}.*

      - name: install sanity test requirements
        run: |
          python -m pip install -r /home/runner/work/test-github-actions/test-github-actions/schamola/test-github-actions/tests/sanity/sanity.requirements

      - name: run sanity test on ansible ${{ matrix.ansible-version }} and python ${{ matrix.python-version }}
        run: |
          ~/.local/bin/ansible-test sanity -v --python ${{ matrix.python-version }} --exclude plugins/modules/_*.py plugins/modules/
